"use strict";

const JARVISTASK_NAMEID_INITCRAWLERMGR      = 'jarvis_initcrawlermgr';
const JARVISTASK_NAMEID_SHELL               = 'jarvis_shell';

exports.JARVISTASK_NAMEID_INITCRAWLERMGR    = JARVISTASK_NAMEID_INITCRAWLERMGR;
exports.JARVISTASK_NAMEID_SHELL             = JARVISTASK_NAMEID_SHELL;